### ISSUE TITLE
Fix introspection and GraphiQL

### ISSUE THREAD

**Issue by Totktonada** [tarantool/graphql.0#179]
It becomes broken after PR #168. There are two reasons for that:

1. Type names with `.` and `$`. Can be fixed in GraphiQL or we can choose another naming convention.
2. Non-standard types InputMap and InputUnion. We can inherit it from Scalar, maybe. InputObject has mandatory `fields` field, but these new types has no such field.

We also need to add introspection test: ask the same query as graphiql does and check some data are returned.
